from PyQt5 import QtCore, QtGui, QtWidgets

class Estado_hotel(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("Estado_hot")
        self.resize(998, 752)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(2, 0, 0, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setStyleSheet("background-color: white;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 500))
        self.widget_4.setStyleSheet("background-color: rgb(178, 210, 201);")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_estado_hotel = QtWidgets.QWidget(self.widget_4)
        self.btn_estado_hotel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_estado_hotel.setStyleSheet("QWidget{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QWidget#btn_estado_hotel:hover{\n"
"border:3px solid Black;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.btn_estado_hotel.setObjectName("btn_estado_hotel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.btn_estado_hotel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.btn_estado_hotel)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.btn_estado_hotel)
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Images/ocupadas.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3.addWidget(self.btn_estado_hotel)
        self.btn_reporte = QtWidgets.QWidget(self.widget_4)
        self.btn_reporte.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_reporte.setStyleSheet("QWidget{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QWidget#btn_reporte:hover{\n"
"border:3px solid Black;\n"
"}")
        self.btn_reporte.setObjectName("btn_reporte")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.btn_reporte)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.btn_reporte)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.btn_reporte)
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Images/salidas.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_3.addWidget(self.btn_reporte)
        self.btn_estado_habita = QtWidgets.QWidget(self.widget_4)
        self.btn_estado_habita.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_estado_habita.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_estado_habita.setStyleSheet("QWidget{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QWidget#btn_estado_habita:hover{\n"
"border:3px solid Black;\n"
"}")
        self.btn_estado_habita.setObjectName("btn_estado_habita")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.btn_estado_habita)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.btn_estado_habita)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.btn_estado_habita)
        self.label_7.setStyleSheet("")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Images/salidas del dia.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_3.addWidget(self.btn_estado_habita)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 11)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid black;\n"
"border-right-color:0px rgb(255, 255, 255);\n"
"border-left-color: 0px rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_5)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Hab_ocu_pag = QtWidgets.QWidget()
        self.Hab_ocu_pag.setStyleSheet("")
        self.Hab_ocu_pag.setObjectName("Hab_ocu_pag")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Hab_ocu_pag)
        self.verticalLayout_8.setContentsMargins(20, 45, 20, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabla_hab_ocup = QtWidgets.QTableWidget(self.Hab_ocu_pag)
        self.tabla_hab_ocup.setEnabled(True)
        self.tabla_hab_ocup.setStyleSheet("font: 10pt \"Roboto\";\n"
"background-color: rgb(250, 255, 237);\n"
"border:1px solid black;")
        self.tabla_hab_ocup.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_hab_ocup.setRowCount(50)
        self.tabla_hab_ocup.setObjectName("tabla_hab_ocup")
        self.tabla_hab_ocup.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_hab_ocup.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_hab_ocup.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_hab_ocup.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_hab_ocup.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_hab_ocup.setHorizontalHeaderItem(4, item)
        self.tabla_hab_ocup.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_hab_ocup.horizontalHeader().setDefaultSectionSize(135)
        self.tabla_hab_ocup.horizontalHeader().setStretchLastSection(True)
        self.tabla_hab_ocup.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.tabla_hab_ocup)
        self.stackedWidget.addWidget(self.Hab_ocu_pag)
        self.Salidas_pag = QtWidgets.QWidget()
        self.Salidas_pag.setObjectName("Salidas_pag")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Salidas_pag)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabla_entra_dia = QtWidgets.QTableWidget(self.Salidas_pag)
        self.tabla_entra_dia.setEnabled(True)
        self.tabla_entra_dia.setStyleSheet("font: 10pt \"Roboto\";\n"
"background-color: rgb(250, 255, 237);\n"
"border:1px solid black;\n"
"border-top: 0px;\n"
"")
        self.tabla_entra_dia.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_entra_dia.setRowCount(50)
        self.tabla_entra_dia.setObjectName("tabla_entra_dia")
        self.tabla_entra_dia.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_entra_dia.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_entra_dia.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_entra_dia.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_entra_dia.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_entra_dia.setHorizontalHeaderItem(4, item)
        self.tabla_entra_dia.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_entra_dia.horizontalHeader().setDefaultSectionSize(135)
        self.tabla_entra_dia.horizontalHeader().setStretchLastSection(True)
        self.tabla_entra_dia.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tabla_entra_dia)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.Salidas_pag)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-top:2px solid black;\n"
"border-bottom:2px solid black;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabla_salid_dia = QtWidgets.QTableWidget(self.Salidas_pag)
        self.tabla_salid_dia.setEnabled(True)
        self.tabla_salid_dia.setStyleSheet("font: 10pt \"Roboto\";\n"
"background-color: rgb(250, 255, 237);\n"
"")
        self.tabla_salid_dia.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_salid_dia.setRowCount(50)
        self.tabla_salid_dia.setObjectName("tabla_salid_dia")
        self.tabla_salid_dia.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salid_dia.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salid_dia.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salid_dia.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salid_dia.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salid_dia.setHorizontalHeaderItem(4, item)
        self.tabla_salid_dia.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_salid_dia.horizontalHeader().setDefaultSectionSize(135)
        self.tabla_salid_dia.horizontalHeader().setStretchLastSection(True)
        self.tabla_salid_dia.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tabla_salid_dia)
        self.stackedWidget.addWidget(self.Salidas_pag)
        self.Estado_hab = QtWidgets.QWidget()
        self.Estado_hab.setObjectName("Estado_hab")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.Estado_hab)
        self.verticalLayout_25.setContentsMargins(25, 20, 25, 0)
        self.verticalLayout_25.setSpacing(25)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_10 = QtWidgets.QWidget(self.Estado_hab)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.widget_10)
        self.label_9.setMinimumSize(QtCore.QSize(40, 40))
        self.label_9.setStyleSheet("border-bottom:1px solid black;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Images/lupa_2.png"))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.linetext_buscar_habitacion = QtWidgets.QLineEdit(self.widget_10)
        self.linetext_buscar_habitacion.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.linetext_buscar_habitacion.setFont(font)
        self.linetext_buscar_habitacion.setStyleSheet("border-top:0px;\n"
"border-bottom:1px solid black;")
        self.linetext_buscar_habitacion.setObjectName("linetext_buscar_habitacion")
        self.horizontalLayout_4.addWidget(self.linetext_buscar_habitacion)
        self.verticalLayout_25.addWidget(self.widget_10)
        self.tabla_estado_hab = QtWidgets.QTableWidget(self.Estado_hab)
        self.tabla_estado_hab.setStyleSheet("font: 10pt \"Roboto\";\n"
"background-color: rgb(250, 255, 237);\n"
"border:1px solid black;")
        self.tabla_estado_hab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_estado_hab.setRowCount(50)
        self.tabla_estado_hab.setObjectName("tabla_estado_hab")
        self.tabla_estado_hab.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_estado_hab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_estado_hab.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_estado_hab.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_estado_hab.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_estado_hab.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_estado_hab.setHorizontalHeaderItem(5, item)
        self.tabla_estado_hab.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_estado_hab.horizontalHeader().setDefaultSectionSize(135)
        self.tabla_estado_hab.horizontalHeader().setStretchLastSection(True)
        self.tabla_estado_hab.verticalHeader().setVisible(False)
        self.verticalLayout_25.addWidget(self.tabla_estado_hab)
        self.stackedWidget.addWidget(self.Estado_hab)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.widget_3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi()
        self.stackedWidget.setCurrentIndex(0)

        self.btn_estado_hotel.mousePressEvent = self.mousePressedEHo
        self.btn_reporte.mousePressEvent = self.mousePressedRep
        self.btn_estado_habita.mousePressEvent = self.mousePressedHa

    def mousePressedEHo(self, event):
        self.stackedWidget.setCurrentIndex(0)
        self.label_8.setText("HISTORIAL DE SALIDAS")

    def mousePressedRep(self, event):
        self.stackedWidget.setCurrentIndex(1)
        self.label_8.setText("REPORTE DIARIO")

    def mousePressedHa(self, event):
        self.stackedWidget.setCurrentIndex(2)
        self.label_8.setText("ESTADO DE HABITACIÓN")  

    def retranslateUi(self):
        self.setWindowTitle("Form")
        self.label_2.setText("ESTADO DEL HOTEL")
        self.label_3.setText( "REPORTE DIARIO")
        self.label_4.setText( "ESTADO DE HABITACIÓN")
        self.label_8.setText( "<html><head/><body><p>HISTORIAL DE SALIDAS</p></body></html>")
        item = self.tabla_hab_ocup.horizontalHeaderItem(0)
        item.setText( "No. Habitación")
        item = self.tabla_hab_ocup.horizontalHeaderItem(1)
        item.setText( "Reponsable")
        item = self.tabla_hab_ocup.horizontalHeaderItem(2)
        item.setText( "Tipo de habitación")
        item = self.tabla_hab_ocup.horizontalHeaderItem(3)
        item.setText( "Costo")
        item = self.tabla_hab_ocup.horizontalHeaderItem(4)
        item.setText( "Fecha de salida")
        item = self.tabla_entra_dia.horizontalHeaderItem(0)
        item.setText( "No. Habitación")
        item = self.tabla_entra_dia.horizontalHeaderItem(1)
        item.setText( "Reponsable")
        item = self.tabla_entra_dia.horizontalHeaderItem(2)
        item.setText( "Tipo de habitación")
        item = self.tabla_entra_dia.horizontalHeaderItem(3)
        item.setText( "Costo")
        item = self.tabla_entra_dia.horizontalHeaderItem(4)
        item.setText( "Fecha de salida")
        self.label.setText( "SALIDAS DEL DIA")
        item = self.tabla_salid_dia.horizontalHeaderItem(0)
        item.setText( "No. Habitación")
        item = self.tabla_salid_dia.horizontalHeaderItem(1)
        item.setText( "Reponsable")
        item = self.tabla_salid_dia.horizontalHeaderItem(2)
        item.setText( "Tipo de habitación")
        item = self.tabla_salid_dia.horizontalHeaderItem(3)
        item.setText( "Costo")
        item = self.tabla_salid_dia.horizontalHeaderItem(4)
        item.setText( "Fecha de salida")
        item = self.tabla_estado_hab.horizontalHeaderItem(0)
        item.setText( "No. Habitación")
        item = self.tabla_estado_hab.horizontalHeaderItem(1)
        item.setText( "Limpieza")
        item = self.tabla_estado_hab.horizontalHeaderItem(2)
        item.setText( "H.Costo")
        item = self.tabla_estado_hab.horizontalHeaderItem(3)
        item.setText( "H.Salida")
        item = self.tabla_estado_hab.horizontalHeaderItem(4)
        item.setText( "H.Vacias")
        item = self.tabla_estado_hab.horizontalHeaderItem(5)
        item.setText( "Otro caso")