from PyQt5 import QtCore, QtGui, QtWidgets


class Salidas(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.resize(946, 751)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(2, 0, 0, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setStyleSheet("background-color: white;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 500))
        self.widget_4.setStyleSheet("background-color: rgb(178, 210, 201);")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_habitaciones_ocu = QtWidgets.QWidget(self.widget_4)
        self.btn_habitaciones_ocu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_habitaciones_ocu.setStyleSheet("QWidget{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QWidget#btn_habitaciones_ocu:hover{\n"
"border:3px solid Black;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.btn_habitaciones_ocu.setObjectName("btn_habitaciones_ocu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.btn_habitaciones_ocu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.btn_habitaciones_ocu)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.btn_habitaciones_ocu)
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Images/ocupadas.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3.addWidget(self.btn_habitaciones_ocu)
        self.btn_salidas = QtWidgets.QWidget(self.widget_4)
        self.btn_salidas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_salidas.setStyleSheet("QWidget{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QWidget#btn_salidas:hover{\n"
"border:3px solid Black;\n"
"}")
        self.btn_salidas.setObjectName("btn_salidas")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.btn_salidas)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.btn_salidas)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.btn_salidas)
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Images/salidas.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_3.addWidget(self.btn_salidas)
        self.btn_salidad_dia = QtWidgets.QWidget(self.widget_4)
        self.btn_salidad_dia.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_salidad_dia.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_salidad_dia.setStyleSheet("QWidget{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QWidget#btn_salidad_dia:hover{\n"
"border:3px solid Black;\n"
"}")
        self.btn_salidad_dia.setObjectName("btn_salidad_dia")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.btn_salidad_dia)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.btn_salidad_dia)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.btn_salidad_dia)
        self.label_7.setStyleSheet("")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Images/salidas del dia.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_3.addWidget(self.btn_salidad_dia)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 11)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:3px solid black;\n"
"border-right-color:0px rgb(255, 255, 255);\n"
"border-left-color: 0px rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_5)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Hab_ocu_pag = QtWidgets.QWidget()
        self.Hab_ocu_pag.setStyleSheet("")
        self.Hab_ocu_pag.setObjectName("Hab_ocu_pag")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Hab_ocu_pag)
        self.verticalLayout_8.setSpacing(7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_13 = QtWidgets.QWidget(self.Hab_ocu_pag)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_9.setSpacing(15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.widget_14)
        self.label_11.setMinimumSize(QtCore.QSize(40, 40))
        self.label_11.setStyleSheet("border-bottom:1px solid black;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Images/lupa_2.png"))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.linetext_buscar_habitacion = QtWidgets.QLineEdit(self.widget_14)
        self.linetext_buscar_habitacion.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.linetext_buscar_habitacion.setFont(font)
        self.linetext_buscar_habitacion.setStyleSheet("border-top:0px;\n"
"border-bottom:1px solid black;")
        self.linetext_buscar_habitacion.setObjectName("linetext_buscar_habitacion")
        self.horizontalLayout_6.addWidget(self.linetext_buscar_habitacion)
        self.buscar_fecha_ho = QtWidgets.QDateEdit(self.widget_14)
        self.buscar_fecha_ho.setMinimumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buscar_fecha_ho.setFont(font)
        self.buscar_fecha_ho.setStyleSheet("font: 10pt \"Verdana\";")
        self.buscar_fecha_ho.setObjectName("buscar_fecha_ho")
        self.buscar_fecha_ho.setCalendarPopup(True)
        self.buscar_fecha_ho.setDisplayFormat("dd/MM/yyyy")
        self.horizontalLayout_6.addWidget(self.buscar_fecha_ho)
        self.verticalLayout_9.addWidget(self.widget_14)
        self.tabla_habita_ocupadas = QtWidgets.QTableWidget(self.widget_13)
        self.tabla_habita_ocupadas.setEnabled(True)
        self.tabla_habita_ocupadas.setStyleSheet("font: 10pt \"Roboto\";\n"
"background-color: rgb(250, 255, 237);\n"
"border:1px solid black;")
        self.tabla_habita_ocupadas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_habita_ocupadas.setRowCount(50)
        self.tabla_habita_ocupadas.setObjectName("tabla_habita_ocupadas")
        self.tabla_habita_ocupadas.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_habita_ocupadas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_habita_ocupadas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_habita_ocupadas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_habita_ocupadas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_habita_ocupadas.setHorizontalHeaderItem(4, item)
        self.tabla_habita_ocupadas.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_habita_ocupadas.horizontalHeader().setDefaultSectionSize(135)
        self.tabla_habita_ocupadas.horizontalHeader().setStretchLastSection(True)
        self.tabla_habita_ocupadas.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.tabla_habita_ocupadas)
        self.verticalLayout_8.addWidget(self.widget_13)
        self.stackedWidget.addWidget(self.Hab_ocu_pag)
        self.Salidas_pag = QtWidgets.QWidget()
        self.Salidas_pag.setObjectName("Salidas_pag")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Salidas_pag)
        self.verticalLayout_7.setContentsMargins(65, 35, 65, 0)
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_11 = QtWidgets.QWidget(self.Salidas_pag)
        self.widget_11.setStyleSheet("QLabel{\n"
"    border-left:2px solid black;\n"
"    font: 10pt \"Roboto\";\n"
"}\n"
"\n"
"QWidget#widget_11{\n"
"    border: 2px solid black;\n"
"    \n"
"}\n"
"\n"
"QLabel#label_10{\n"
"    border:0px;\n"
"    font: 10pt \"Roboto\";\n"
"}\n"
"\n"
"Line{\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    font: 10pt \"Roboto\";\n"
"}\n"
"")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_5.setContentsMargins(-1, 3, 11, 3)
        self.horizontalLayout_5.setSpacing(11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_12 = QtWidgets.QWidget(self.widget_11)
        self.widget_12.setMaximumSize(QtCore.QSize(350, 16777215))
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.widget_12)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.no_habit = QtWidgets.QLineEdit(self.widget_12)
        self.no_habit.setMinimumSize(QtCore.QSize(0, 40))
        self.no_habit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.no_habit.setStyleSheet("font: 10pt \"Verdana\";")
        self.no_habit.setObjectName("no_habit")
        self.verticalLayout_10.addWidget(self.no_habit)
        self.horizontalLayout_5.addWidget(self.widget_12)
        self.line_2 = QtWidgets.QFrame(self.widget_11)
        self.line_2.setMinimumSize(QtCore.QSize(0, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.cb_llaves = QtWidgets.QCheckBox(self.widget_11)
        self.cb_llaves.setEnabled(True)
        self.cb_llaves.setStyleSheet("")
        self.cb_llaves.setTristate(False)
        self.cb_llaves.setObjectName("cb_llaves")
        self.horizontalLayout_5.addWidget(self.cb_llaves)
        self.line = QtWidgets.QFrame(self.widget_11)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.cb_toallas = QtWidgets.QCheckBox(self.widget_11)
        self.cb_toallas.setMinimumSize(QtCore.QSize(0, 43))
        self.cb_toallas.setObjectName("cb_toallas")
        self.horizontalLayout_5.addWidget(self.cb_toallas)
        self.line_3 = QtWidgets.QFrame(self.widget_11)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.cb_controles = QtWidgets.QCheckBox(self.widget_11)
        self.cb_controles.setObjectName("cb_controles")
        self.horizontalLayout_5.addWidget(self.cb_controles)
        self.verticalLayout_7.addWidget(self.widget_11)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem)
        self.label_14 = QtWidgets.QLabel(self.Salidas_pag)
        self.label_14.setStyleSheet("font: 11pt \"Roboto\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.observaciones = QtWidgets.QTextEdit(self.Salidas_pag)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.observaciones.sizePolicy().hasHeightForWidth())
        self.observaciones.setSizePolicy(sizePolicy)
        self.observaciones.setMinimumSize(QtCore.QSize(0, 120))
        self.observaciones.setMaximumSize(QtCore.QSize(16777215, 177))
        self.observaciones.setStyleSheet("font: 10pt \"Roboto\";\n"
"border-left: 1px solid black;\n"
"border-right: 1px solid black;\n"
"border-top:1px solid black;\n"
"border-bottom: 1px solid blue;")
        self.observaciones.setObjectName("observaciones")
        self.verticalLayout_7.addWidget(self.observaciones)
        self.btn_finalizar = QtWidgets.QPushButton(self.Salidas_pag)
        self.btn_finalizar.setMinimumSize(QtCore.QSize(250, 50))
        self.btn_finalizar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(156, 255, 171);\n"
"    font: 87 11pt \"Roboto Black\";\n"
"    color: black;\n"
"}")
        self.btn_finalizar.setObjectName("btn_finalizar")
        self.verticalLayout_7.addWidget(self.btn_finalizar, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.Salidas_pag)
        self.page_historial = QtWidgets.QWidget()
        self.page_historial.setObjectName("page_historial")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_historial)
        self.verticalLayout_25.setContentsMargins(25, 20, 25, 0)
        self.verticalLayout_25.setSpacing(25)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_10 = QtWidgets.QWidget(self.page_historial)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.widget_10)
        self.label_9.setMinimumSize(QtCore.QSize(40, 40))
        self.label_9.setStyleSheet("border-bottom:1px solid black;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Images/lupa_2.png"))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.buscar_salidas_dia = QtWidgets.QLineEdit(self.widget_10)
        self.buscar_salidas_dia.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.buscar_salidas_dia.setFont(font)
        self.buscar_salidas_dia.setStyleSheet("border-top:0px;\n"
"border-bottom:1px solid black;")
        self.buscar_salidas_dia.setObjectName("buscar_salidas_dia")
        self.horizontalLayout_4.addWidget(self.buscar_salidas_dia)
        self.verticalLayout_25.addWidget(self.widget_10)
        self.tabla_salidas_dia = QtWidgets.QTableWidget(self.page_historial)
        self.tabla_salidas_dia.setStyleSheet("font: 10pt \"Roboto\";\n"
"background-color: rgb(250, 255, 237);\n"
"border:1px solid black;")
        self.tabla_salidas_dia.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_salidas_dia.setRowCount(50)
        self.tabla_salidas_dia.setObjectName("tabla_salidas_dia")
        self.tabla_salidas_dia.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salidas_dia.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salidas_dia.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salidas_dia.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salidas_dia.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_salidas_dia.setHorizontalHeaderItem(4, item)
        self.tabla_salidas_dia.horizontalHeader().setCascadingSectionResizes(False)
        self.tabla_salidas_dia.horizontalHeader().setDefaultSectionSize(135)
        self.tabla_salidas_dia.horizontalHeader().setStretchLastSection(True)
        self.tabla_salidas_dia.verticalHeader().setVisible(False)
        self.verticalLayout_25.addWidget(self.tabla_salidas_dia)
        self.stackedWidget.addWidget(self.page_historial)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.widget_3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi()
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.btn_habitaciones_ocu.mousePressEvent = self.mousePressed_HO
        self.btn_salidas.mousePressEvent = self.mousePressed_Salid
        self.btn_salidad_dia.mousePressEvent = self.mousePressed_SD

    def mousePressed_HO(self, event):
        self.stackedWidget.setCurrentIndex(0)
        self.label_8.setText("HABITACIONES OCUPADAS")

    def mousePressed_Salid(self, event):
        self.stackedWidget.setCurrentIndex(1)
        self.label_8.setText("SALIDAS")

    def mousePressed_SD(self, event):
        self.stackedWidget.setCurrentIndex(2)
        self.label_8.setText("SALIDAS DEL DIA")   

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("Form", "HABITACIONES OCUPADAS"))
        self.label_3.setText(_translate("Form", "SALIDAS"))
        self.label_4.setText(_translate("Form", "SALIDAS DEL DIA"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p>HABITACIONES OCUPADAS</p></body></html>"))
        item = self.tabla_habita_ocupadas.horizontalHeaderItem(0)
        item.setText(_translate("Form", "No. Habitación"))
        item = self.tabla_habita_ocupadas.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Reponsable"))
        item = self.tabla_habita_ocupadas.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tipo de habitación"))
        item = self.tabla_habita_ocupadas.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Costo"))
        item = self.tabla_habita_ocupadas.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Fecha de salida"))
        self.label_10.setText(_translate("Form", "No. Habitación"))
        self.cb_llaves.setText(_translate("Form", "Llaves"))
        self.cb_toallas.setText(_translate("Form", "Toallas"))
        self.cb_controles.setText(_translate("Form", "Controles"))
        self.label_14.setText(_translate("Form", "  Observaciones:"))
        self.btn_finalizar.setText(_translate("Form", "FINALIZAR"))
        item = self.tabla_salidas_dia.horizontalHeaderItem(0)
        item.setText(_translate("Form", "No. Habitación"))
        item = self.tabla_salidas_dia.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Reponsable"))
        item = self.tabla_salidas_dia.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tipo de habitación"))
        item = self.tabla_salidas_dia.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Costo"))
        item = self.tabla_salidas_dia.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Fecha de salida"))


